#Specifies the level of warning to be generated by the compiler. Valid warning levels for n range from 0 to 4.
string(REGEX REPLACE "/W[0-9]" "/W4" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

# C4127 - conditional expression is constant
# C4714 - marked as __forceinline but not inlined
# C4505 - unreferenced local function has been removed (impossible to deactive selectively)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHsc /wd4127 /wd4505 /wd4714")
